name: Generate M3U Playlists

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'generate_playlists.py'
      - '.github/workflows/generate_playlists.yml'

jobs:
  build-playlists:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: List Playlists Directory Before
        run: |
          echo "Contents of playlists/ before running script:"
          ls -la playlists/ || echo "playlists/ directory does not exist"

      - name: Run Playlist Generation Script
        run: python generate_playlists.py

      - name: List Playlists Directory After
        run: |
          echo "Contents of playlists/ after running script:"
          ls -la playlists/

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if the M3U file exists
          if [ -f playlists/extracted_playlist.m3u ]; then
            echo "M3U file exists, staging for commit..."
            git add playlists/extracted_playlist.m3u
            git add playlists/script.log || echo "No log file to add"
            # Commit changes, even if minimal
            git commit -m "Update M3U playlists [skip ci]" || echo "No changes to commit"
            # Pull with rebase to integrate remote changes
            echo "Pulling latest changes from remote..."
            git fetch origin
            git rebase origin/main
            if [ $? -ne 0 ]; then
              echo "Rebase failed, aborting..."
              git rebase --abort
              exit 1
            fi
            # Retry push with delay
            n=0
            until [ $n -ge 5 ]
            do
              git push && break
              n=$((n+1))
              echo "Push failed. Retrying attempt $n/5..."
              sleep 15
            done
            if [ $n -ge 5 ]; then
              echo "Failed to push changes after multiple attempts."
              exit 1
            fi
          else
            echo "No M3U file found in playlists/. Nothing to commit."
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
